import type { Employee } from "../../../types";
import type { UiLanguage } from "../../utils/localization";

export function employeePageText(language: UiLanguage) {
  if (language === "en") {
    return {
      title: "Employees",
      description: "Manage employees, roles, contracts and availability.",
      addEmployee: "Add employee",
      addEmployeeHint: "Create the employee first, then set availability and time off.",
      addRolesFirst: "Add roles before assigning them to employees.",
      addTimeOff: "Add time off",
      activate: "Activate",
      active: "Active",
      availability: "Availability",
      availabilityHelp: "Cannot work blocks automatic scheduling. Preferences guide the scheduler when possible.",
      availabilitySaved: "Availability saved.",
      canLeadRole: "Can lead this role",
      canWorkWeekends: "Can work weekends",
      chooseEmployeeFirst: "Choose an employee first.",
      close: "Close",
      dateFrom: "Date from",
      dateTo: "Date to",
      day: "Day",
      dayLevel: "Day-level",
      daysPerWeek: "Days / week",
      deactivate: "Deactivate",
      delete: "Delete",
      descriptionShort: "Employees",
      details: "Details",
      editEmployee: (employee: Employee | null) =>
        employee
          ? `Edit ${employee.first_name} ${employee.last_name}`
          : "Edit employee",
      editEmployeeHint: "Edit details, roles, work rules, availability and time off in one place.",
      email: "Email",
      employeeActivated: "Employee activated.",
      employeeAdded: "Employee added.",
      employeeDeactivated: "Employee deactivated.",
      employeeUpdated: "Employee updated.",
      employmentType: "Employment type",
      experience: "Experience",
      firstName: "First name",
      hoursPerDay: "Hours / day",
      hoursPerWeek: "Hours / week",
      inactive: "Inactive",
      lastName: "Last name",
      maxConsecutiveDays: "Max consecutive days",
      noEmail: "No email",
      noEmployeesFound: "No employees found.",
      noPhone: "No phone",
      noReason: "No reason",
      noRoles: "No roles are available.",
      noRolesAssigned: "No roles",
      noShiftTemplates: "Add active shift templates before setting shift availability.",
      noTimeOff: "No time off has been recorded for this employee.",
      notes: "Notes",
      phone: "Phone",
      preferredRole: "Preferred role",
      reason: "Reason",
      roleAssignments: "Role assignments",
      roles: "Roles",
      saveBeforeAvailability: "Save the employee before editing availability or time off.",
      saveEmployee: "Save employee",
      saveFailed: "Employee could not be saved.",
      saveNewEmployee: "Save new employee",
      saving: "Saving...",
      search: "Search employees",
      searchPlaceholder: "Search by name, phone, email, role or notes",
      selectEmployeePrompt: "Select an employee or add a new one to edit details, roles, contract rules and availability.",
      shift: "Shift",
      showing: (visible: number, total: number) => `Showing ${visible} of ${total}`,
      status: "Status",
      timeOff: "Time off",
      timeOffDeleted: "Time off deleted.",
      timeOffSaved: "Time off saved.",
      type: "Type",
      wholeDay: "Whole day",
      workRules: "Work rules"
    };
  }

  return {
    title: "Εργαζόμενοι",
    description: "Διαχείριση εργαζομένων, ρόλων, σύμβασης και διαθεσιμότητας.",
    addEmployee: "Προσθήκη εργαζομένου",
    addEmployeeHint: "Δημιουργήστε πρώτα τον εργαζόμενο και μετά ορίστε διαθεσιμότητα και άδειες.",
    addRolesFirst: "Προσθέστε ρόλους πριν τους αναθέσετε σε εργαζόμενους.",
    addTimeOff: "Προσθήκη άδειας",
    activate: "Ενεργοποίηση",
    active: "Ενεργός",
    availability: "Διαθεσιμότητα",
    availabilityHelp: "Το Δεν μπορεί μπλοκάρει τον αυτόματο προγραμματισμό. Οι προτιμήσεις βοηθούν το πρόγραμμα όπου γίνεται.",
    availabilitySaved: "Η διαθεσιμότητα αποθηκεύτηκε.",
    canLeadRole: "Μπορεί να είναι υπεύθυνος ρόλου",
    canWorkWeekends: "Μπορεί να δουλεύει Σαββατοκύριακο",
    chooseEmployeeFirst: "Επιλέξτε πρώτα εργαζόμενο.",
    close: "Κλείσιμο",
    dateFrom: "Από",
    dateTo: "Έως",
    day: "Ημέρα",
    dayLevel: "Ημέρα",
    daysPerWeek: "Ημέρες / εβδομάδα",
    deactivate: "Απενεργοποίηση",
    delete: "Διαγραφή",
    descriptionShort: "Εργαζόμενοι",
    details: "Στοιχεία",
    editEmployee: (employee: Employee | null) =>
      employee
        ? `Επεξεργασία ${employee.first_name} ${employee.last_name}`
        : "Επεξεργασία εργαζομένου",
    editEmployeeHint: "Επεξεργαστείτε στοιχεία, ρόλους, σύμβαση, διαθεσιμότητα και άδειες σε ένα σημείο.",
    email: "Email",
    employeeActivated: "Ο εργαζόμενος ενεργοποιήθηκε.",
    employeeAdded: "Ο εργαζόμενος προστέθηκε.",
    employeeDeactivated: "Ο εργαζόμενος απενεργοποιήθηκε.",
    employeeUpdated: "Ο εργαζόμενος ενημερώθηκε.",
    employmentType: "Τύπος απασχόλησης",
    experience: "Προϋπηρεσία",
    firstName: "Όνομα",
    hoursPerDay: "Ώρες / ημέρα",
    hoursPerWeek: "Ώρες / εβδομάδα",
    inactive: "Ανενεργός",
    lastName: "Επώνυμο",
    maxConsecutiveDays: "Μέγιστες συνεχόμενες ημέρες",
    noEmail: "Χωρίς email",
    noEmployeesFound: "Δεν βρέθηκαν εργαζόμενοι.",
    noPhone: "Χωρίς τηλέφωνο",
    noReason: "Χωρίς αιτιολογία",
    noRoles: "Δεν υπάρχουν διαθέσιμοι ρόλοι.",
    noRolesAssigned: "Χωρίς ρόλους",
    noShiftTemplates: "Προσθέστε ενεργές βάρδιες πριν ορίσετε διαθεσιμότητα βάρδιας.",
    noTimeOff: "Δεν έχει καταχωρηθεί άδεια για αυτόν τον εργαζόμενο.",
    notes: "Σημειώσεις",
    phone: "Τηλέφωνο",
    preferredRole: "Προτιμώμενος ρόλος",
    reason: "Αιτιολογία",
    roleAssignments: "Ρόλοι εργαζομένου",
    roles: "Ρόλοι",
    saveBeforeAvailability: "Αποθηκεύστε τον εργαζόμενο πριν επεξεργαστείτε διαθεσιμότητα ή άδειες.",
    saveEmployee: "Αποθήκευση εργαζομένου",
    saveFailed: "Δεν ήταν δυνατή η αποθήκευση εργαζομένου.",
    saveNewEmployee: "Αποθήκευση νέου εργαζομένου",
    saving: "Αποθήκευση...",
    search: "Αναζήτηση εργαζομένων",
    searchPlaceholder: "Αναζήτηση με όνομα, τηλέφωνο, email, ρόλο ή σημειώσεις",
    selectEmployeePrompt: "Επιλέξτε εργαζόμενο ή προσθέστε νέο για να επεξεργαστείτε στοιχεία, ρόλους, σύμβαση και διαθεσιμότητα.",
    shift: "Βάρδια",
    showing: (visible: number, total: number) => `Εμφάνιση ${visible} από ${total}`,
    status: "Κατάσταση",
    timeOff: "Άδειες / Ρεπό",
    timeOffDeleted: "Η άδεια διαγράφηκε.",
    timeOffSaved: "Η άδεια αποθηκεύτηκε.",
    type: "Τύπος",
    wholeDay: "Ολόκληρη ημέρα",
    workRules: "Σύμβαση / Κανόνες εργασίας"
  };
}
