import type { Employee } from "../../../types";
import type { UiLanguage } from "../../utils/localization";

export function employeePageText(language: UiLanguage) {
  if (language === "en") {
    return {
      title: "Employees",
      description: "Manage employees, roles, contracts and availability.",
      addEmployee: "Add employee",
      addEmployeeHint: "Create the employee first, then set availability and time off.",
      addRolesFirst: "Add roles before assigning them to employees.",
      addTimeOff: "Add time off",
      activate: "Activate",
      active: "Active",
      availability: "Availability",
      availabilityHelp: "Cannot work blocks automatic scheduling. Preferences guide the scheduler when possible.",
      availabilitySaved: "Availability saved.",
      canLeadRole: "Can lead this role",
      canWorkWeekends: "Can work weekends",
      chooseEmployeeFirst: "Choose an employee first.",
      close: "Close",
      dateFrom: "Date from",
      dateTo: "Date to",
      day: "Day",
      dayLevel: "Day-level",
      daysPerWeek: "Days / week",
      deactivate: "Deactivate",
      delete: "Delete",
      descriptionShort: "Employees",
      details: "Details",
      editEmployee: (employee: Employee | null) =>
        employee
          ? `Edit ${employee.first_name} ${employee.last_name}`
          : "Edit employee",
      editEmployeeHint: "Edit details, roles, work rules, availability and time off in one place.",
      email: "Email",
      employeeActivated: "Employee activated.",
      employeeAdded: "Employee added.",
      employeeDeactivated: "Employee deactivated.",
      employeeUpdated: "Employee updated.",
      employmentType: "Employment type",
      experience: "Experience",
      firstName: "First name",
      hoursPerDay: "Hours / day",
      hoursPerWeek: "Hours / week",
      inactive: "Inactive",
      lastName: "Last name",
      maxConsecutiveDays: "Max consecutive days",
      noEmail: "No email",
      noEmployeesFound: "No employees found.",
      noPhone: "No phone",
      noReason: "No reason",
      noRoles: "No roles are available.",
      noRolesAssigned: "No roles",
      noShiftTemplates: "Add active shift templates before setting shift availability.",
      noTimeOff: "No time off has been recorded for this employee.",
      notes: "Notes",
      phone: "Phone",
      preferredRole: "Preferred role",
      reason: "Reason",
      roleAssignments: "Role assignments",
      roles: "Roles",
      saveBeforeAvailability: "Save the employee before editing availability or time off.",
      saveEmployee: "Save employee",
      saveFailed: "Employee could not be saved.",
      saveNewEmployee: "Save new employee",
      saving: "Saving...",
      search: "Search employees",
      searchPlaceholder: "Search by name, phone, email, role or notes",
      selectEmployeePrompt: "Select an employee or add a new one to edit details, roles, contract rules and availability.",
      shift: "Shift",
      showing: (visible: number, total: number) => `Showing ${visible} of ${total}`,
      status: "Status",
      timeOff: "Time off",
      timeOffDeleted: "Time off deleted.",
      timeOffSaved: "Time off saved.",
      type: "Type",
      wholeDay: "Whole day",
      workRules: "Work rules"
    };
  }

  return {
    title: "Ξ•ΟΞ³Ξ±Ξ¶ΟΞΌΞµΞ½ΞΏΞΉ",
    description: "Ξ”ΞΉΞ±Ο‡ΞµΞ―ΟΞΉΟƒΞ· ΞµΟΞ³Ξ±Ξ¶ΞΏΞΌΞ­Ξ½Ο‰Ξ½, ΟΟΞ»Ο‰Ξ½, ΟƒΟΞΌΞ²Ξ±ΟƒΞ·Ο‚ ΞΊΞ±ΞΉ Ξ΄ΞΉΞ±ΞΈΞµΟƒΞΉΞΌΟΟ„Ξ·Ο„Ξ±Ο‚.",
    addEmployee: "Ξ ΟΞΏΟƒΞΈΞ®ΞΊΞ· ΞµΟΞ³Ξ±Ξ¶ΞΏΞΌΞ­Ξ½ΞΏΟ…",
    addEmployeeHint: "Ξ”Ξ·ΞΌΞΉΞΏΟ…ΟΞ³Ξ®ΟƒΟ„Ξµ Ο€ΟΟΟ„Ξ± Ο„ΞΏΞ½ ΞµΟΞ³Ξ±Ξ¶ΟΞΌΞµΞ½ΞΏ ΞΊΞ±ΞΉ ΞΌΞµΟ„Ξ¬ ΞΏΟΞ―ΟƒΟ„Ξµ Ξ΄ΞΉΞ±ΞΈΞµΟƒΞΉΞΌΟΟ„Ξ·Ο„Ξ± ΞΊΞ±ΞΉ Ξ¬Ξ΄ΞµΞΉΞµΟ‚.",
    addRolesFirst: "Ξ ΟΞΏΟƒΞΈΞ­ΟƒΟ„Ξµ ΟΟΞ»ΞΏΟ…Ο‚ Ο€ΟΞΉΞ½ Ο„ΞΏΟ…Ο‚ Ξ±Ξ½Ξ±ΞΈΞ­ΟƒΞµΟ„Ξµ ΟƒΞµ ΞµΟΞ³Ξ±Ξ¶ΞΏΞΌΞ­Ξ½ΞΏΟ…Ο‚.",
    addTimeOff: "Ξ ΟΞΏΟƒΞΈΞ®ΞΊΞ· Ξ¬Ξ΄ΞµΞΉΞ±Ο‚",
    activate: "Ξ•Ξ½ΞµΟΞ³ΞΏΟ€ΞΏΞ―Ξ·ΟƒΞ·",
    active: "Ξ•Ξ½ΞµΟΞ³ΟΟ‚",
    availability: "Ξ”ΞΉΞ±ΞΈΞµΟƒΞΉΞΌΟΟ„Ξ·Ο„Ξ±",
    availabilityHelp: "Ξ¤ΞΏ Ξ”ΞµΞ½ ΞΌΟ€ΞΏΟΞµΞ― ΞΌΟ€Ξ»ΞΏΞΊΞ¬ΟΞµΞΉ Ο„ΞΏΞ½ Ξ±Ο…Ο„ΟΞΌΞ±Ο„ΞΏ Ο€ΟΞΏΞ³ΟΞ±ΞΌΞΌΞ±Ο„ΞΉΟƒΞΌΟ. ΞΞΉ Ο€ΟΞΏΟ„ΞΉΞΌΞ®ΟƒΞµΞΉΟ‚ Ξ²ΞΏΞ·ΞΈΞΏΟΞ½ Ο„ΞΏ Ο€ΟΟΞ³ΟΞ±ΞΌΞΌΞ± ΟΟ€ΞΏΟ… Ξ³Ξ―Ξ½ΞµΟ„Ξ±ΞΉ.",
    availabilitySaved: "Ξ— Ξ΄ΞΉΞ±ΞΈΞµΟƒΞΉΞΌΟΟ„Ξ·Ο„Ξ± Ξ±Ο€ΞΏΞΈΞ·ΞΊΞµΟΟ„Ξ·ΞΊΞµ.",
    canLeadRole: "ΞΟ€ΞΏΟΞµΞ― Ξ½Ξ± ΞµΞ―Ξ½Ξ±ΞΉ Ο…Ο€ΞµΟΞΈΟ…Ξ½ΞΏΟ‚ ΟΟΞ»ΞΏΟ…",
    canWorkWeekends: "ΞΟ€ΞΏΟΞµΞ― Ξ½Ξ± Ξ΄ΞΏΟ…Ξ»ΞµΟΞµΞΉ Ξ£Ξ±Ξ²Ξ²Ξ±Ο„ΞΏΞΊΟΟΞΉΞ±ΞΊΞΏ",
    chooseEmployeeFirst: "Ξ•Ο€ΞΉΞ»Ξ­ΞΎΟ„Ξµ Ο€ΟΟΟ„Ξ± ΞµΟΞ³Ξ±Ξ¶ΟΞΌΞµΞ½ΞΏ.",
    close: "ΞΞ»ΞµΞ―ΟƒΞΉΞΌΞΏ",
    dateFrom: "Ξ‘Ο€Ο",
    dateTo: "ΞΟ‰Ο‚",
    day: "Ξ—ΞΌΞ­ΟΞ±",
    dayLevel: "Ξ—ΞΌΞ­ΟΞ±",
    daysPerWeek: "Ξ—ΞΌΞ­ΟΞµΟ‚ / ΞµΞ²Ξ΄ΞΏΞΌΞ¬Ξ΄Ξ±",
    deactivate: "Ξ‘Ο€ΞµΞ½ΞµΟΞ³ΞΏΟ€ΞΏΞ―Ξ·ΟƒΞ·",
    delete: "Ξ”ΞΉΞ±Ξ³ΟΞ±Ο†Ξ®",
    descriptionShort: "Ξ•ΟΞ³Ξ±Ξ¶ΟΞΌΞµΞ½ΞΏΞΉ",
    details: "Ξ£Ο„ΞΏΞΉΟ‡ΞµΞ―Ξ±",
    editEmployee: (employee: Employee | null) =>
      employee
        ? `Ξ•Ο€ΞµΞΎΞµΟΞ³Ξ±ΟƒΞ―Ξ± ${employee.first_name} ${employee.last_name}`
        : "Ξ•Ο€ΞµΞΎΞµΟΞ³Ξ±ΟƒΞ―Ξ± ΞµΟΞ³Ξ±Ξ¶ΞΏΞΌΞ­Ξ½ΞΏΟ…",
    editEmployeeHint: "Ξ•Ο€ΞµΞΎΞµΟΞ³Ξ±ΟƒΟ„ΞµΞ―Ο„Ξµ ΟƒΟ„ΞΏΞΉΟ‡ΞµΞ―Ξ±, ΟΟΞ»ΞΏΟ…Ο‚, ΟƒΟΞΌΞ²Ξ±ΟƒΞ·, Ξ΄ΞΉΞ±ΞΈΞµΟƒΞΉΞΌΟΟ„Ξ·Ο„Ξ± ΞΊΞ±ΞΉ Ξ¬Ξ΄ΞµΞΉΞµΟ‚ ΟƒΞµ Ξ­Ξ½Ξ± ΟƒΞ·ΞΌΞµΞ―ΞΏ.",
    email: "Email",
    employeeActivated: "Ξ ΞµΟΞ³Ξ±Ξ¶ΟΞΌΞµΞ½ΞΏΟ‚ ΞµΞ½ΞµΟΞ³ΞΏΟ€ΞΏΞΉΞ®ΞΈΞ·ΞΊΞµ.",
    employeeAdded: "Ξ ΞµΟΞ³Ξ±Ξ¶ΟΞΌΞµΞ½ΞΏΟ‚ Ο€ΟΞΏΟƒΟ„Ξ­ΞΈΞ·ΞΊΞµ.",
    employeeDeactivated: "Ξ ΞµΟΞ³Ξ±Ξ¶ΟΞΌΞµΞ½ΞΏΟ‚ Ξ±Ο€ΞµΞ½ΞµΟΞ³ΞΏΟ€ΞΏΞΉΞ®ΞΈΞ·ΞΊΞµ.",
    employeeUpdated: "Ξ ΞµΟΞ³Ξ±Ξ¶ΟΞΌΞµΞ½ΞΏΟ‚ ΞµΞ½Ξ·ΞΌΞµΟΟΞΈΞ·ΞΊΞµ.",
    employmentType: "Ξ¤ΟΟ€ΞΏΟ‚ Ξ±Ο€Ξ±ΟƒΟ‡ΟΞ»Ξ·ΟƒΞ·Ο‚",
    experience: "Ξ ΟΞΏΟ‹Ο€Ξ·ΟΞµΟƒΞ―Ξ±",
    firstName: "ΞΞ½ΞΏΞΌΞ±",
    hoursPerDay: "ΞΟΞµΟ‚ / Ξ·ΞΌΞ­ΟΞ±",
    hoursPerWeek: "ΞΟΞµΟ‚ / ΞµΞ²Ξ΄ΞΏΞΌΞ¬Ξ΄Ξ±",
    inactive: "Ξ‘Ξ½ΞµΞ½ΞµΟΞ³ΟΟ‚",
    lastName: "Ξ•Ο€ΟΞ½Ο…ΞΌΞΏ",
    maxConsecutiveDays: "ΞΞ­Ξ³ΞΉΟƒΟ„ΞµΟ‚ ΟƒΟ…Ξ½ΞµΟ‡ΟΞΌΞµΞ½ΞµΟ‚ Ξ·ΞΌΞ­ΟΞµΟ‚",
    noEmail: "Ξ§Ο‰ΟΞ―Ο‚ email",
    noEmployeesFound: "Ξ”ΞµΞ½ Ξ²ΟΞ­ΞΈΞ·ΞΊΞ±Ξ½ ΞµΟΞ³Ξ±Ξ¶ΟΞΌΞµΞ½ΞΏΞΉ.",
    noPhone: "Ξ§Ο‰ΟΞ―Ο‚ Ο„Ξ·Ξ»Ξ­Ο†Ο‰Ξ½ΞΏ",
    noReason: "Ξ§Ο‰ΟΞ―Ο‚ Ξ±ΞΉΟ„ΞΉΞΏΞ»ΞΏΞ³Ξ―Ξ±",
    noRoles: "Ξ”ΞµΞ½ Ο…Ο€Ξ¬ΟΟ‡ΞΏΟ…Ξ½ Ξ΄ΞΉΞ±ΞΈΞ­ΟƒΞΉΞΌΞΏΞΉ ΟΟΞ»ΞΏΞΉ.",
    noRolesAssigned: "Ξ§Ο‰ΟΞ―Ο‚ ΟΟΞ»ΞΏΟ…Ο‚",
    noShiftTemplates: "Ξ ΟΞΏΟƒΞΈΞ­ΟƒΟ„Ξµ ΞµΞ½ΞµΟΞ³Ξ­Ο‚ Ξ²Ξ¬ΟΞ΄ΞΉΞµΟ‚ Ο€ΟΞΉΞ½ ΞΏΟΞ―ΟƒΞµΟ„Ξµ Ξ΄ΞΉΞ±ΞΈΞµΟƒΞΉΞΌΟΟ„Ξ·Ο„Ξ± Ξ²Ξ¬ΟΞ΄ΞΉΞ±Ο‚.",
    noTimeOff: "Ξ”ΞµΞ½ Ξ­Ο‡ΞµΞΉ ΞΊΞ±Ο„Ξ±Ο‡Ο‰ΟΞ·ΞΈΞµΞ― Ξ¬Ξ΄ΞµΞΉΞ± Ξ³ΞΉΞ± Ξ±Ο…Ο„ΟΞ½ Ο„ΞΏΞ½ ΞµΟΞ³Ξ±Ξ¶ΟΞΌΞµΞ½ΞΏ.",
    notes: "Ξ£Ξ·ΞΌΞµΞΉΟΟƒΞµΞΉΟ‚",
    phone: "Ξ¤Ξ·Ξ»Ξ­Ο†Ο‰Ξ½ΞΏ",
    preferredRole: "Ξ ΟΞΏΟ„ΞΉΞΌΟΞΌΞµΞ½ΞΏΟ‚ ΟΟΞ»ΞΏΟ‚",
    reason: "Ξ‘ΞΉΟ„ΞΉΞΏΞ»ΞΏΞ³Ξ―Ξ±",
    roleAssignments: "Ξ΅ΟΞ»ΞΏΞΉ ΞµΟΞ³Ξ±Ξ¶ΞΏΞΌΞ­Ξ½ΞΏΟ…",
    roles: "Ξ΅ΟΞ»ΞΏΞΉ",
    saveBeforeAvailability: "Ξ‘Ο€ΞΏΞΈΞ·ΞΊΞµΟΟƒΟ„Ξµ Ο„ΞΏΞ½ ΞµΟΞ³Ξ±Ξ¶ΟΞΌΞµΞ½ΞΏ Ο€ΟΞΉΞ½ ΞµΟ€ΞµΞΎΞµΟΞ³Ξ±ΟƒΟ„ΞµΞ―Ο„Ξµ Ξ΄ΞΉΞ±ΞΈΞµΟƒΞΉΞΌΟΟ„Ξ·Ο„Ξ± Ξ® Ξ¬Ξ΄ΞµΞΉΞµΟ‚.",
    saveEmployee: "Ξ‘Ο€ΞΏΞΈΞ®ΞΊΞµΟ…ΟƒΞ· ΞµΟΞ³Ξ±Ξ¶ΞΏΞΌΞ­Ξ½ΞΏΟ…",
    saveFailed: "Ξ”ΞµΞ½ Ξ®Ο„Ξ±Ξ½ Ξ΄Ο…Ξ½Ξ±Ο„Ξ® Ξ· Ξ±Ο€ΞΏΞΈΞ®ΞΊΞµΟ…ΟƒΞ· ΞµΟΞ³Ξ±Ξ¶ΞΏΞΌΞ­Ξ½ΞΏΟ….",
    saveNewEmployee: "Ξ‘Ο€ΞΏΞΈΞ®ΞΊΞµΟ…ΟƒΞ· Ξ½Ξ­ΞΏΟ… ΞµΟΞ³Ξ±Ξ¶ΞΏΞΌΞ­Ξ½ΞΏΟ…",
    saving: "Ξ‘Ο€ΞΏΞΈΞ®ΞΊΞµΟ…ΟƒΞ·...",
    search: "Ξ‘Ξ½Ξ±Ξ¶Ξ®Ο„Ξ·ΟƒΞ· ΞµΟΞ³Ξ±Ξ¶ΞΏΞΌΞ­Ξ½Ο‰Ξ½",
    searchPlaceholder: "Ξ‘Ξ½Ξ±Ξ¶Ξ®Ο„Ξ·ΟƒΞ· ΞΌΞµ ΟΞ½ΞΏΞΌΞ±, Ο„Ξ·Ξ»Ξ­Ο†Ο‰Ξ½ΞΏ, email, ΟΟΞ»ΞΏ Ξ® ΟƒΞ·ΞΌΞµΞΉΟΟƒΞµΞΉΟ‚",
    selectEmployeePrompt: "Ξ•Ο€ΞΉΞ»Ξ­ΞΎΟ„Ξµ ΞµΟΞ³Ξ±Ξ¶ΟΞΌΞµΞ½ΞΏ Ξ® Ο€ΟΞΏΟƒΞΈΞ­ΟƒΟ„Ξµ Ξ½Ξ­ΞΏ Ξ³ΞΉΞ± Ξ½Ξ± ΞµΟ€ΞµΞΎΞµΟΞ³Ξ±ΟƒΟ„ΞµΞ―Ο„Ξµ ΟƒΟ„ΞΏΞΉΟ‡ΞµΞ―Ξ±, ΟΟΞ»ΞΏΟ…Ο‚, ΟƒΟΞΌΞ²Ξ±ΟƒΞ· ΞΊΞ±ΞΉ Ξ΄ΞΉΞ±ΞΈΞµΟƒΞΉΞΌΟΟ„Ξ·Ο„Ξ±.",
    shift: "Ξ’Ξ¬ΟΞ΄ΞΉΞ±",
    showing: (visible: number, total: number) => `Ξ•ΞΌΟ†Ξ¬Ξ½ΞΉΟƒΞ· ${visible} Ξ±Ο€Ο ${total}`,
    status: "ΞΞ±Ο„Ξ¬ΟƒΟ„Ξ±ΟƒΞ·",
    timeOff: "Ξ†Ξ΄ΞµΞΉΞµΟ‚ / Ξ΅ΞµΟ€Ο",
    timeOffDeleted: "Ξ— Ξ¬Ξ΄ΞµΞΉΞ± Ξ΄ΞΉΞ±Ξ³ΟΞ¬Ο†Ξ·ΞΊΞµ.",
    timeOffSaved: "Ξ— Ξ¬Ξ΄ΞµΞΉΞ± Ξ±Ο€ΞΏΞΈΞ·ΞΊΞµΟΟ„Ξ·ΞΊΞµ.",
    type: "Ξ¤ΟΟ€ΞΏΟ‚",
    wholeDay: "ΞΞ»ΟΞΊΞ»Ξ·ΟΞ· Ξ·ΞΌΞ­ΟΞ±",
    workRules: "Ξ£ΟΞΌΞ²Ξ±ΟƒΞ· / ΞΞ±Ξ½ΟΞ½ΞµΟ‚ ΞµΟΞ³Ξ±ΟƒΞ―Ξ±Ο‚"
  };
}
